-- Optional Supabase persistence for the BDC Value Map.
-- The existing analyzer still uses analysis_cache. This table stores dated
-- valuation snapshots and preserves history by inserting a new row per refresh.

create table if not exists bdc_value_snapshots (
  id bigint generated by default as identity primary key,
  ticker text not null,
  cik text,
  snapshot_date timestamptz not null default now(),
  as_of timestamptz,
  snapshot_json jsonb not null default '{}'::jsonb,
  stale boolean not null default false,
  error text
);

create index if not exists bdc_value_snapshots_ticker_date_idx
  on bdc_value_snapshots (ticker, snapshot_date desc);

create index if not exists bdc_value_snapshots_as_of_idx
  on bdc_value_snapshots (as_of desc);
